use_frameworks!

target 'BlinkingLabel_Example' do
  pod 'BlinkingLabel', :path => '../'

  target 'BlinkingLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
